services:
  web:
    image: alexander003/php-app:latest
    build:
      target: web
      context: .
    env_file:
      - .env # Load environment variables
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html # Mount application code into the container
    depends_on:
      - db
    networks:
      - app_network

  db:
    platform: "linux/amd64"
    image: postgres:14 # Use PostgreSQL image
    env_file:
      - .env # Use .env file for sensitive information
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    command: postgres --max-connections=100 --bind-address=0.0.0.0
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - dbdata:/var/lib/postgresql/data # Persist database data
    networks:
      - app_network

volumes:
  dbdata:
    driver: local

networks:
  app_network:
    driver: bridge
