name: Build, deploy, and set up PHP app on Azure Web App

on:
  push:
    branches: ["docker"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: kaskada-cafe     # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # Path to your PHP project
  PHP_VERSION: '8.2'                  # PHP version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, pdo, bcmath, intl, pgsql

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          composer --version

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: .  # Use current directory

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: myapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .  # Deploy current directory

      - name: Run database setup script
        run: |
          echo "Running database setup script..."
          php ./db_setup.php
